modLoader = "javafml"
loaderVersion = "[2,)"
license = "lGPL3"
issueTrackerURL = "https://github.com/terrarium-earth/Pastel/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId = "spectrum"
version = "${version}"
displayName = "Spectrum"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pastel"
logoFile="icon.png"
credits="Salad Cat, Ashley, Robotgiggle, Pizzacalz0ne, Lily, HoneyHive, Electro_593, Noaaaaaaaaan"
authors="Azzyypaaras"
description='''Do flowers dream of the moon?'''


[[mixins]]
config="spectrum.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.spectrum]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.spectrum]]
modId="modonomicon"
type="required"
versionRange="[,)"
ordering="NONE"
side="BOTH"
