package de.dafuqs.spectrum.progression;

import de.dafuqs.spectrum.*;
import de.dafuqs.spectrum.progression.advancement.AzureDikeChargeCriterion;
import de.dafuqs.spectrum.progression.advancement.BlockBrokenCriterion;
import de.dafuqs.spectrum.progression.advancement.BloodOrchidPluckingCriterion;
import de.dafuqs.spectrum.progression.advancement.CinderhearthSmeltingCriterion;
import de.dafuqs.spectrum.progression.advancement.CompletedMultiblockCriterion;
import de.dafuqs.spectrum.progression.advancement.ConfirmationButtonPressedCriterion;
import de.dafuqs.spectrum.progression.advancement.CrystalApothecaryCollectingCriterion;
import de.dafuqs.spectrum.progression.advancement.CrystallarieumGrownCriterion;
import de.dafuqs.spectrum.progression.advancement.DivinityTickCriterion;
import de.dafuqs.spectrum.progression.advancement.EnchanterCraftingCriterion;
import de.dafuqs.spectrum.progression.advancement.EnchanterEnchantingCriterion;
import de.dafuqs.spectrum.progression.advancement.EnchantmentUpgradedCriterion;
import de.dafuqs.spectrum.progression.advancement.FluidDippingCriterion;
import de.dafuqs.spectrum.progression.advancement.FusionShrineCraftingCriterion;
import de.dafuqs.spectrum.progression.advancement.HummingstoneHymnCriterion;
import de.dafuqs.spectrum.progression.advancement.InertiaUsedCriterion;
import de.dafuqs.spectrum.progression.advancement.InkContainerInteractionCriterion;
import de.dafuqs.spectrum.progression.advancement.InkProjectileKillingCriterion;
import de.dafuqs.spectrum.progression.advancement.JeopardantKillCriterion;
import de.dafuqs.spectrum.progression.advancement.LootFunctionTriggerCriterion;
import de.dafuqs.spectrum.progression.advancement.MemoryManifestingCriterion;
import de.dafuqs.spectrum.progression.advancement.NaturesStaffConversionCriterion;
import de.dafuqs.spectrum.progression.advancement.PairedFoodEatenCriterion;
import de.dafuqs.spectrum.progression.advancement.PastelNetworkCreationCriterion;
import de.dafuqs.spectrum.progression.advancement.PastelNodeUpgradeCriterion;
import de.dafuqs.spectrum.progression.advancement.PedestalCraftingCriterion;
import de.dafuqs.spectrum.progression.advancement.PedestalRecipeCalculatedCriterion;
import de.dafuqs.spectrum.progression.advancement.PotionWorkshopBrewingCriterion;
import de.dafuqs.spectrum.progression.advancement.PotionWorkshopCraftingCriterion;
import de.dafuqs.spectrum.progression.advancement.PreservationCheckCriterion;
import de.dafuqs.spectrum.progression.advancement.SlimeSizingCriterion;
import de.dafuqs.spectrum.progression.advancement.SpectrumFishingRodHookedCriterion;
import de.dafuqs.spectrum.progression.advancement.SpiritInstillerCraftingCriterion;
import de.dafuqs.spectrum.progression.advancement.TakeOffBeltJumpCriterion;
import de.dafuqs.spectrum.progression.advancement.TitrationBarrelTappingCriterion;
import de.dafuqs.spectrum.progression.advancement.TrinketChangeCriterion;
import de.dafuqs.spectrum.progression.advancement.UpgradePlaceCriterion;
import net.minecraft.advancements.*;
import net.minecraft.core.registries.*;
import net.neoforged.bus.api.*;
import net.neoforged.neoforge.registries.*;

public class SpectrumAdvancementCriteria {

	private static final DeferredRegister<CriterionTrigger<?>> REGISTER = DeferredRegister.create(Registries.TRIGGER_TYPE, SpectrumCommon.MOD_ID);

	public static PedestalRecipeCalculatedCriterion PEDESTAL_RECIPE_CALCULATED = new PedestalRecipeCalculatedCriterion();
	public static PedestalCraftingCriterion PEDESTAL_CRAFTING = new PedestalCraftingCriterion();
	public static FusionShrineCraftingCriterion FUSION_SHRINE_CRAFTING = new FusionShrineCraftingCriterion();
	public static CompletedMultiblockCriterion COMPLETED_MULTIBLOCK = new CompletedMultiblockCriterion();
	public static BlockBrokenCriterion BLOCK_BROKEN = new BlockBrokenCriterion();
	public static LootFunctionTriggerCriterion LOOT_FUNCTION_TRIGGER = new LootFunctionTriggerCriterion();
	public static NaturesStaffConversionCriterion NATURES_STAFF_USE = new NaturesStaffConversionCriterion();
	public static EnchanterCraftingCriterion ENCHANTER_CRAFTING = new EnchanterCraftingCriterion();
	public static EnchanterEnchantingCriterion ENCHANTER_ENCHANTING = new EnchanterEnchantingCriterion();
	public static EnchantmentUpgradedCriterion ENCHANTER_UPGRADING = new EnchantmentUpgradedCriterion();
	public static InertiaUsedCriterion INERTIA_USED = new InertiaUsedCriterion();
	public static AzureDikeChargeCriterion AZURE_DIKE_CHARGE = new AzureDikeChargeCriterion();
	public static TrinketChangeCriterion TRINKET_CHANGE = new TrinketChangeCriterion();
	public static PotionWorkshopBrewingCriterion POTION_WORKSHOP_BREWING = new PotionWorkshopBrewingCriterion();
	public static PotionWorkshopCraftingCriterion POTION_WORKSHOP_CRAFTING = new PotionWorkshopCraftingCriterion();
	public static TakeOffBeltJumpCriterion TAKE_OFF_BELT_JUMP = new TakeOffBeltJumpCriterion();
	public static InkContainerInteractionCriterion INK_CONTAINER_INTERACTION = new InkContainerInteractionCriterion();
	public static JeopardantKillCriterion JEOPARDANT_KILL = new JeopardantKillCriterion();
	public static MemoryManifestingCriterion MEMORY_MANIFESTING = new MemoryManifestingCriterion();
	public static SpiritInstillerCraftingCriterion SPIRIT_INSTILLER_CRAFTING = new SpiritInstillerCraftingCriterion();
	public static SlimeSizingCriterion SLIME_SIZING = new SlimeSizingCriterion();
	public static CrystalApothecaryCollectingCriterion CRYSTAL_APOTHECARY_COLLECTING = new CrystalApothecaryCollectingCriterion();
	public static UpgradePlaceCriterion UPGRADE_PLACING = new UpgradePlaceCriterion();
	public static CrystallarieumGrownCriterion CRYSTALLARIEUM_GROWING = new CrystallarieumGrownCriterion();
	public static CinderhearthSmeltingCriterion CINDERHEARTH_SMELTING = new CinderhearthSmeltingCriterion();
	public static InkProjectileKillingCriterion KILLED_BY_INK_PROJECTILE = new InkProjectileKillingCriterion();
	public static SpectrumFishingRodHookedCriterion FISHING_ROD_HOOKED = new SpectrumFishingRodHookedCriterion();
	public static TitrationBarrelTappingCriterion TITRATION_BARREL_TAPPING = new TitrationBarrelTappingCriterion();
	public static ConfirmationButtonPressedCriterion CONFIRMATION_BUTTON_PRESSED = new ConfirmationButtonPressedCriterion();
	public static BloodOrchidPluckingCriterion BLOOD_ORCHID_PLUCKING = new BloodOrchidPluckingCriterion();
	public static DivinityTickCriterion DIVINITY_TICK = new DivinityTickCriterion();
	public static PairedFoodEatenCriterion CONDITIONAL_FOOD_EATEN = new PairedFoodEatenCriterion();
	public static HummingstoneHymnCriterion CREATE_HUMMINGSTONE_HYMN = new HummingstoneHymnCriterion();
	public static PastelNetworkCreationCriterion PASTEL_NETWORK_CREATING = new PastelNetworkCreationCriterion();
	public static PastelNodeUpgradeCriterion PASTEL_NODE_UPGRADING = new PastelNodeUpgradeCriterion();
	public static PreservationCheckCriterion PRESERVATION_CHECK = new PreservationCheckCriterion();
	public static FluidDippingCriterion FLUID_DIPPING = new FluidDippingCriterion();

	public static void register(IEventBus bus) {
		REGISTER.register(PedestalRecipeCalculatedCriterion.ID.getPath(), () -> PEDESTAL_RECIPE_CALCULATED);
		REGISTER.register(PedestalCraftingCriterion.ID.getPath(), () -> PEDESTAL_CRAFTING);
		REGISTER.register(FusionShrineCraftingCriterion.ID.getPath(), () -> FUSION_SHRINE_CRAFTING);
		REGISTER.register(CompletedMultiblockCriterion.ID.getPath(), () -> COMPLETED_MULTIBLOCK);
		REGISTER.register(BlockBrokenCriterion.ID.getPath(), () -> BLOCK_BROKEN);
		REGISTER.register(LootFunctionTriggerCriterion.ID.getPath(), () -> LOOT_FUNCTION_TRIGGER);
		REGISTER.register(NaturesStaffConversionCriterion.ID.getPath(), () -> NATURES_STAFF_USE);
		REGISTER.register(EnchanterCraftingCriterion.ID.getPath(), () -> ENCHANTER_CRAFTING);
		REGISTER.register(EnchanterEnchantingCriterion.ID.getPath(), () -> ENCHANTER_ENCHANTING);
		REGISTER.register(EnchantmentUpgradedCriterion.ID.getPath(), () -> ENCHANTER_UPGRADING);
		REGISTER.register(InertiaUsedCriterion.ID.getPath(), () -> INERTIA_USED);
		REGISTER.register(AzureDikeChargeCriterion.ID.getPath(), () -> AZURE_DIKE_CHARGE);
		REGISTER.register(TrinketChangeCriterion.ID.getPath(), () -> TRINKET_CHANGE);
		REGISTER.register(PotionWorkshopBrewingCriterion.ID.getPath(), () -> POTION_WORKSHOP_BREWING);
		REGISTER.register(PotionWorkshopCraftingCriterion.ID.getPath(), () -> POTION_WORKSHOP_CRAFTING);
		REGISTER.register(TakeOffBeltJumpCriterion.ID.getPath(), () -> TAKE_OFF_BELT_JUMP);
		REGISTER.register(InkContainerInteractionCriterion.ID.getPath(), () -> INK_CONTAINER_INTERACTION);
		REGISTER.register(JeopardantKillCriterion.ID.getPath(), () -> JEOPARDANT_KILL);
		REGISTER.register(MemoryManifestingCriterion.ID.getPath(), () -> MEMORY_MANIFESTING);
		REGISTER.register(SpiritInstillerCraftingCriterion.ID.getPath(), () -> SPIRIT_INSTILLER_CRAFTING);
		REGISTER.register(SlimeSizingCriterion.ID.getPath(), () -> SLIME_SIZING);
		REGISTER.register(CrystalApothecaryCollectingCriterion.ID.getPath(), () -> CRYSTAL_APOTHECARY_COLLECTING);
		REGISTER.register(UpgradePlaceCriterion.ID.getPath(), () -> UPGRADE_PLACING);
		REGISTER.register(CrystallarieumGrownCriterion.ID.getPath(), () -> CRYSTALLARIEUM_GROWING);
		REGISTER.register(CinderhearthSmeltingCriterion.ID.getPath(), () -> CINDERHEARTH_SMELTING);
		REGISTER.register(InkProjectileKillingCriterion.ID.getPath(), () -> KILLED_BY_INK_PROJECTILE);
		REGISTER.register(SpectrumFishingRodHookedCriterion.ID.getPath(), () -> FISHING_ROD_HOOKED);
		REGISTER.register(TitrationBarrelTappingCriterion.ID.getPath(), () -> TITRATION_BARREL_TAPPING);
		REGISTER.register(ConfirmationButtonPressedCriterion.ID.getPath(), () -> CONFIRMATION_BUTTON_PRESSED);
		REGISTER.register(BloodOrchidPluckingCriterion.ID.getPath(), () -> BLOOD_ORCHID_PLUCKING);
		REGISTER.register(DivinityTickCriterion.ID.getPath(), () -> DIVINITY_TICK);
		REGISTER.register(PairedFoodEatenCriterion.ID.getPath(), () -> CONDITIONAL_FOOD_EATEN);
		REGISTER.register(HummingstoneHymnCriterion.ID.getPath(), () -> CREATE_HUMMINGSTONE_HYMN);
		REGISTER.register(PastelNetworkCreationCriterion.ID.getPath(), () -> PASTEL_NETWORK_CREATING);
		REGISTER.register(PastelNodeUpgradeCriterion.ID.getPath(), () -> PASTEL_NODE_UPGRADING);
		REGISTER.register(PreservationCheckCriterion.ID.getPath(), () -> PRESERVATION_CHECK);
		REGISTER.register(FluidDippingCriterion.ID.getPath(), () -> FLUID_DIPPING);

		REGISTER.register(bus);
	}
	
}
