package earth.terrarium.pastel.data;

import com.google.common.collect.Maps;
import com.google.common.collect.Sets;
import com.google.gson.JsonElement;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.data.models.blockstates.BlockStateGenerator;
import net.minecraft.data.models.model.DelegatedModel;
import net.minecraft.data.models.model.ModelLocationUtils;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

public abstract class AbstractModelProvider implements DataProvider {
    private final PackOutput.PathProvider blockStatePathProvider;
    private final PackOutput.PathProvider modelPathProvider;
    private final String modId;

    public AbstractModelProvider(PackOutput output, String modId) {
        this.blockStatePathProvider = output.createPathProvider(PackOutput.Target.RESOURCE_PACK, "blockstates");
        this.modelPathProvider = output.createPathProvider(PackOutput.Target.RESOURCE_PACK, "models");
        this.modId = modId;
    }
    @Override
    public CompletableFuture<?> run(CachedOutput output) {
        Map<Block, BlockStateGenerator> blockStateGenerators = Maps.newHashMap();
        Consumer<BlockStateGenerator> blocKStateGeneratorCollector = stateGenerator -> {
            Block block = stateGenerator.getBlock();
            BlockStateGenerator existingStateGenerator = blockStateGenerators.put(block, stateGenerator);
            if (existingStateGenerator != null) {
                throw new IllegalStateException("Duplicate blockstate definition for " + block);
            }
        };
        Map<ResourceLocation, Supplier<JsonElement>> modelGenerators = Maps.newHashMap();
        Set<Item> skippedAutoGeneratedModels = Sets.newHashSet();
        BiConsumer<ResourceLocation, Supplier<JsonElement>> modelGeneratorCollector = (modelLocation, modelGenerator) -> {
            Supplier<JsonElement> existingModelGenerator = modelGenerators.put(modelLocation, modelGenerator);
            if (existingModelGenerator != null) {
                throw new IllegalStateException("Duplicate model definition for " + modelLocation);
            }
        };

        Consumer<Item> skippedAutoGeneratedModelCollector = skippedAutoGeneratedModels::add;
        generateBlockModels(new BlockModelGenerators(blocKStateGeneratorCollector, modelGeneratorCollector, skippedAutoGeneratedModelCollector));
        generateItemModels(new ItemModelGenerators(modelGeneratorCollector));

        List<Block> missingBlocks = BuiltInRegistries.BLOCK
            .entrySet()
            .stream()
            .filter(entry -> entry.getKey().location().getNamespace().equals(modId))
            .map(Map.Entry::getValue)
            .filter(block -> !blockStateGenerators.containsKey(block))
            .toList();

        if (!missingBlocks.isEmpty()) {
            // throw new IllegalStateException("Missing blockstate definitions for: " + missingBlocks);
        }
        BuiltInRegistries.BLOCK.forEach(block -> {
            if (!block.builtInRegistryHolder().getKey().location().getNamespace().equals(modId)) {
                return;
            }

            Item item = Item.BY_BLOCK.get(block);

            if (item != null) {
                if (skippedAutoGeneratedModels.contains(item)) {
                    return;
                }

                ResourceLocation modelLocation = ModelLocationUtils.getModelLocation(item);
                if (!modelGenerators.containsKey(modelLocation)) {
                    modelGenerators.put(modelLocation, new DelegatedModel(ModelLocationUtils.getModelLocation(block)));
                }
            }
        });

        return CompletableFuture.allOf(
            this.saveCollection(output, blockStateGenerators, block -> this.blockStatePathProvider.json(block.builtInRegistryHolder().key().location())),
            this.saveCollection(output, modelGenerators, this.modelPathProvider::json)
        );
    }

    protected abstract void generateBlockModels(BlockModelGenerators generators);
    protected abstract void generateItemModels(ItemModelGenerators generators);

    private <T> CompletableFuture<?> saveCollection(
        CachedOutput output,
        Map<T, ? extends Supplier<JsonElement>> objectToJsonMap,
        Function<T, Path> resolveObjectPath
    ) {
        return CompletableFuture.allOf(objectToJsonMap.entrySet().stream().map(modelGenerator -> {
            Path path = resolveObjectPath.apply(modelGenerator.getKey());
            JsonElement model = modelGenerator.getValue().get();
            return DataProvider.saveStable(output, model, path);
        }).toArray(CompletableFuture[]::new));
    }

    @Override
    public final String getName() {
        return "Model Definitions";
    }
}
